mcell_mc2d_K: 25
mcell_mc2d_T_edge: 0.025
mcell_mc2d_proj_blur: 0.02
mcell_mc2d_max_confu_deg: 5
mcell_mc2d_edge_asym: FALSE
mcell_mc2d_k_expand_inout_factor: NULL

mcell_mc2d_height: 1200
mcell_mc2d_width: 1200

mcp_heatmap_width: 2000
mcell_mc2d_plot_key: FALSE
